LOAD DATA
INFILE 'LIBROS.csv'
INTO TABLE LIBRO
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  idLibro      INTEGER EXTERNAL,
  isbn         CHAR,
  titulo       CHAR,
  afinidad     INTEGER EXTERNAL,
  leido        INTEGER EXTERNAL
)
